PROJECT = top
PROJECT_DESCRIPTION = New project
PROJECT_VERSION = 0.1.0

# Make sure we know where the applications are located.
ROOT_DIR ?= ../..
APPS_DIR ?= ..
DEPS_DIR ?= ../../deps

include $(ROOT_DIR)/erlang.mk
